plugins {
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.142' apply false
    id 'net.fabricmc.fabric-loom-remap' version "${fabric_loom_version}" apply false
}

subprojects {
    apply plugin: 'java-library'

    java {
        withSourcesJar()
        toolchain.languageVersion = JavaLanguageVersion.of(21)
    }

    jar {
        from rootProject.file('LICENSE')
    }

    sourcesJar {
        from rootProject.file('LICENSE')
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
